/*
 * Copyright 2022 Patrik Karlström <patrik@trixon.se>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.yaya;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.HierarchyBoundsListener;
import java.awt.event.HierarchyEvent;
import java.awt.image.BufferedImage;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JComponent;
import javax.swing.JPanel;
import se.trixon.yaya.dice.DiceBoard;
import se.trixon.yaya.dice.DiceBoard.RollEvent;
import se.trixon.yaya.gamedef.GameType;
import se.trixon.yaya.gamedef.GameTypeLoader;
import se.trixon.yaya.scorecard.ScoreCard;
import se.trixon.yaya.scorecard.ScoreCardObservable.ScoreCardEvent;

/**
 *
 * @author Patrik Karlström
 */
public class GamePanel extends JPanel implements Observer {

    private DiceBoard mDiceBoard;
    private boolean mRollable = true;
    private int mNumOfPlayers;
    private ScoreCard mScoreCard;
    private final Options mOptions = Options.getInstance();
    private GameType mGameType;
    private BufferedImage mBackgroundImage;

    /**
     * Creates new form YayaPanel
     */
    public GamePanel() {
        init();
        initComponents();
        //GameDef.getInstance().init();
        initInitialLayout();
        setBackgroundImage(Yaya.getImage("images/wood_panel1.jpg"));
    }

    public void centerInParent() {
        JComponent topPanel = (JComponent) getParent();
        if (topPanel != null && topPanel.getHeight() > 0 && topPanel.getWidth() > 0) {
        }
    }

    public String getGameTitle() {
        return mGameType.getTitle();
    }

    @Override
    public void update(Graphics g) {
        paint(g);
    }

    private void init() {
        addHierarchyBoundsListener(new HierarchyBoundsListener() {

            @Override
            public void ancestorMoved(HierarchyEvent evt) {
            }

            @Override
            public void ancestorResized(HierarchyEvent evt) {
                centerInParent();
            }
        });
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof RollEvent) {
            switch ((RollEvent) arg) {
                case PRE_ROLL:
                    mScoreCard.setEnabledUndo(false);
                    mRollable = mScoreCard.isRollable();
                    if (mRollable) {
                        mScoreCard.newRoll();
                        mDiceBoard.roll();
                    }

                    break;

                case POST_ROLL:
                    mScoreCard.parseDice(mDiceBoard.getValues());
                    break;
            }
        }

        if (arg instanceof ScoreCardEvent) {
            switch ((ScoreCardEvent) arg) {
                case GAME_OVER:
                    mDiceBoard.gameOver();
                    break;

                case REGISTER:
                    mDiceBoard.newTurn();
                    break;

                case UNDO:
                    mDiceBoard.undo();
                    break;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 255, 153));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void newGame() {
//        if (numOfPlayers != settings.getNumOfPlayers()) {
//            numOfPlayers = settings.getNumOfPlayers();
//            initRule(settings.getRule());
//        }
        initGame();
        mScoreCard.newGame();
        mDiceBoard.newTurn();

        for (int i = 0; i < mScoreCard.getHeaderColumn().getRows().length; i++) {
            var row = mScoreCard.getHeaderColumn().getRows()[i];
            System.out.println("%d\t%s".formatted(i, row.getLabel().getText()));
        }
    }

    private void initDiceBoard() {
        mDiceBoard.addObserver(this);
        mDiceBoard.setDiceTofloor(1000);
        mDiceBoard.setMaxRollCount(mGameType.getNumOfRolls());
        add(mDiceBoard.getPanel(), BorderLayout.SOUTH);
    }

    private void initGame() {
        removeAll();
        mGameType = GameTypeLoader.getInstance().getType(mOptions.getGameTypeId());
        mNumOfPlayers = mOptions.getNumOfPlayers();

        mDiceBoard = new DiceBoard(mGameType.getNumOfDice());
        mScoreCard = new ScoreCard();
        initScoreCard();
        initDiceBoard();
    }

    private void initInitialLayout() {
        add(new DiceBoard(0).getPanel(), BorderLayout.SOUTH);
    }

    private void initScoreCard() {
        mScoreCard.getObservable().addObserver(this);
        add(mScoreCard.getCard(), BorderLayout.CENTER);
    }

    public BufferedImage getBackgroundImage() {
        return mBackgroundImage;
    }

    public void setBackgroundImage(BufferedImage backgroundImage) {
        mBackgroundImage = backgroundImage;
    }

    @Override
    public void paint(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        if (mBackgroundImage != null) {
            for (int i = 0; i < (getHeight() / mBackgroundImage.getHeight()) + 1; i++) {
                if (getWidth() < mBackgroundImage.getWidth()) {
                    g2.drawImage(mBackgroundImage, 0, i * mBackgroundImage.getHeight(), null);
                } else {
                    g2.drawImage(mBackgroundImage, 0, i * mBackgroundImage.getHeight(), getWidth(), mBackgroundImage.getHeight(), null);
                }
            }
        }

        super.paint(g);
        g2.dispose();
    }
}
